### ISSUE TITLE
blobs migration to Azure

### ISSUE THREAD

**Issue by cs2pooja** [shweta0318/micron#2]
Hi Aditi, I have a query like:
I want to migrate TBs of files/blobs from some shared network to Azure container. How we can efficiently migrate or transferred  all files speedily ? there is AZCopy tool which does this but it takes couple of weeks to migrate all blobs.

**Comment by shweta0318** [comment]
https://azure.microsoft.com/en-us/services/databox/ Please refer the link for your query.
